ubuntu:
  build: .
  ports:
   - '8080:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test-ubuntu
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
alpine:
  build: .
  dockerfile: Dockerfile-alpine
  ports:
   - '8081:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test-alpine
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
centos:
  build: .
  dockerfile: Dockerfile-centos
  ports:
   - '8082:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test-centos
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
ubuntu17:
  build: .
  dockerfile: Dockerfile-ubuntu-17.10
  ports:
   - '8083:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test-ubuntu-17.10
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
ubuntu18:
  build: .
  dockerfile: Dockerfile-ubuntu-18.04
  ports:
   - '8084:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test-ubuntu-18.04
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
