name: main

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_BASE: behance/docker-base
    strategy:
      matrix:
        props:
        - Dockerfile: Dockerfile-ubuntu-18.04
          suffix: ubuntu-18.04
        - Dockerfile: Dockerfile-ubuntu-20.04
          suffix: ubuntu-20.04
        - Dockerfile: Dockerfile-alpine
          suffix: alpine
        - Dockerfile: Dockerfile-centos-7
          suffix: centos-7
        - Dockerfile: Dockerfile-centos-8
          suffix: centos-8
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Add tag suffix
        if: matrix.props.suffix
        run: |
          echo TAG_SUFFIX="-${{ matrix.props.suffix }}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: meta
        if: github.event_name != 'pull_request'
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_BASE }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=false
            suffix=${{ env.TAG_SUFFIX }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build + push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.props.Dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
